# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remastersys.ui'
#
# Created: Sat Sep 21 21:34:18 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Remastersys(object):
    def setupUi(self, Remastersys):
        Remastersys.setObjectName(_fromUtf8("Remastersys"))
        Remastersys.resize(715, 580)
        Remastersys.setMinimumSize(QtCore.QSize(715, 580))
        Remastersys.setMaximumSize(QtCore.QSize(715, 580))
        self.centralWidget = QtGui.QWidget(Remastersys)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 691, 141))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/remastersys-large.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 210, 661, 321))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName(_fromUtf8("page_1"))
        self.console1 = QConsoleWidget(self.page_1)
        self.console1.setGeometry(QtCore.QRect(13, 16, 641, 311))
        self.console1.setObjectName(_fromUtf8("console1"))
        self.mainImg = QtGui.QLabel(self.page_1)
        self.mainImg.setGeometry(QtCore.QRect(210, 50, 221, 221))
        self.mainImg.setText(_fromUtf8(""))
        self.mainImg.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/main.png")))
        self.mainImg.setObjectName(_fromUtf8("mainImg"))
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.console2 = QConsoleWidget(self.page_2)
        self.console2.setGeometry(QtCore.QRect(13, 16, 641, 311))
        self.console2.setObjectName(_fromUtf8("console2"))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayoutWidget = QtGui.QWidget(self.page_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(6, 10, 181, 291))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splashImgBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.splashImgBtn.setMinimumSize(QtCore.QSize(175, 30))
        self.splashImgBtn.setMaximumSize(QtCore.QSize(175, 30))
        self.splashImgBtn.setObjectName(_fromUtf8("splashImgBtn"))
        self.verticalLayout.addWidget(self.splashImgBtn)
        self.grubImgBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.grubImgBtn.setMinimumSize(QtCore.QSize(175, 30))
        self.grubImgBtn.setMaximumSize(QtCore.QSize(175, 30))
        self.grubImgBtn.setObjectName(_fromUtf8("grubImgBtn"))
        self.verticalLayout.addWidget(self.grubImgBtn)
        self.plymouthBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.plymouthBtn.setMinimumSize(QtCore.QSize(175, 30))
        self.plymouthBtn.setMaximumSize(QtCore.QSize(175, 30))
        self.plymouthBtn.setObjectName(_fromUtf8("plymouthBtn"))
        self.verticalLayout.addWidget(self.plymouthBtn)
        self.userSettingBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.userSettingBtn.setMinimumSize(QtCore.QSize(175, 30))
        self.userSettingBtn.setMaximumSize(QtCore.QSize(175, 30))
        self.userSettingBtn.setObjectName(_fromUtf8("userSettingBtn"))
        self.verticalLayout.addWidget(self.userSettingBtn)
        self.configureBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.configureBtn.setMinimumSize(QtCore.QSize(175, 30))
        self.configureBtn.setMaximumSize(QtCore.QSize(175, 30))
        self.configureBtn.setObjectName(_fromUtf8("configureBtn"))
        self.verticalLayout.addWidget(self.configureBtn)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.page_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(202, 10, 451, 291))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.label_5 = QtGui.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(220, 50, 221, 221))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/main.png")))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.textEdit = QtGui.QTextEdit(self.page_5)
        self.textEdit.setGeometry(QtCore.QRect(13, 16, 631, 301))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.stackedWidget.addWidget(self.page_5)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(39, 150, 641, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.backupBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.backupBtn.setObjectName(_fromUtf8("backupBtn"))
        self.horizontalLayout.addWidget(self.backupBtn)
        self.distBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.distBtn.setObjectName(_fromUtf8("distBtn"))
        self.horizontalLayout.addWidget(self.distBtn)
        self.customBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.customBtn.setObjectName(_fromUtf8("customBtn"))
        self.horizontalLayout.addWidget(self.customBtn)
        self.clearBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.clearBtn.setObjectName(_fromUtf8("clearBtn"))
        self.horizontalLayout.addWidget(self.clearBtn)
        self.checklogBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.checklogBtn.setObjectName(_fromUtf8("checklogBtn"))
        self.horizontalLayout.addWidget(self.checklogBtn)
        self.quitBtn = QtGui.QPushButton(self.centralWidget)
        self.quitBtn.setGeometry(QtCore.QRect(590, 540, 98, 27))
        self.quitBtn.setObjectName(_fromUtf8("quitBtn"))
        self.aboutBtn = QtGui.QPushButton(self.centralWidget)
        self.aboutBtn.setGeometry(QtCore.QRect(40, 540, 98, 27))
        self.aboutBtn.setObjectName(_fromUtf8("aboutBtn"))
        Remastersys.setCentralWidget(self.centralWidget)

        self.retranslateUi(Remastersys)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Remastersys)

    def retranslateUi(self, Remastersys):
        Remastersys.setWindowTitle(QtGui.QApplication.translate("Remastersys", "Remastersys", None, QtGui.QApplication.UnicodeUTF8))
        self.splashImgBtn.setText(QtGui.QApplication.translate("Remastersys", "Splash Image", None, QtGui.QApplication.UnicodeUTF8))
        self.grubImgBtn.setText(QtGui.QApplication.translate("Remastersys", "Grub Image", None, QtGui.QApplication.UnicodeUTF8))
        self.plymouthBtn.setText(QtGui.QApplication.translate("Remastersys", "Plymouth Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.userSettingBtn.setText(QtGui.QApplication.translate("Remastersys", "User Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.configureBtn.setText(QtGui.QApplication.translate("Remastersys", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Remastersys", "Select a 640x480 png file for the live menu background", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Remastersys", "Select a picture for the Grub menu background ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Remastersys", "Create and select a plymouth theme", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Remastersys", "Copy user settings to /etc/skel and be the default for all new users", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Remastersys", "Customize the settings for remastersys", None, QtGui.QApplication.UnicodeUTF8))
        self.backupBtn.setText(QtGui.QApplication.translate("Remastersys", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.distBtn.setText(QtGui.QApplication.translate("Remastersys", "Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.customBtn.setText(QtGui.QApplication.translate("Remastersys", "Customize", None, QtGui.QApplication.UnicodeUTF8))
        self.clearBtn.setText(QtGui.QApplication.translate("Remastersys", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.checklogBtn.setText(QtGui.QApplication.translate("Remastersys", "Check Log", None, QtGui.QApplication.UnicodeUTF8))
        self.quitBtn.setText(QtGui.QApplication.translate("Remastersys", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutBtn.setText(QtGui.QApplication.translate("Remastersys", "About", None, QtGui.QApplication.UnicodeUTF8))

from terminalwidget import QConsoleWidget
import remastersys_rc
